### ISSUE TITLE
please update 'frontend system design' !

### ISSUE THREAD

**Issue by FailLone** [pietrop/pietrop.github.io#19]
https://github.com/pietrop/pietrop.github.io/blob/master/categories/blog/2021-06-16-front-end-system-design.md

great article!

could you remind me if you update?(there is a 'draft' in title)

**Comment by pietrop** [comment]
Thanks, I think, for now, that’s pretty much a final draft. Unless there’s feedback for improvements. 
thanks for flagging that, I removed draft from the title 😄
